### ISSUE TITLE
Connecting with a non-English client.

### ISSUE THREAD

**Issue by brotalnia** [S7urp33/ChronoEmu#15]
I saw in the latest commit that you've hardcoded the client build number to 1.12.1.5875. I have not tested, but non-English clients have a different build number, so this may result in some players being unable to login. The clients are functionally interchangeable and you are supposed to be able to join any 1.12 server no matter the client language.

As you can see in the attached image the Chinese language Vanilla client is version 1.12.3.6141.
![wow 1 12 zhcn](https://cloud.githubusercontent.com/assets/6519171/20959172/357b1ca4-bc62-11e6-9679-13771fd621c8.png)

**Comment by S7urp33** [comment]
I will make an adjustment so that it will max out at 7000, the reasoning for removing it from the config is individuals will setup the entire core then ask why are receiving the "unable to validate" game version and the question would have to be re-answered over and over to check the client build.

**Comment by S7urp33** [comment]
The max build is now set to 7000 and the minbuild is 5875. We can adjust this to fit but it will allow you to login since your client is 6141. I'm going to assume that the client build numbers for 1.2.x shouldn't exceed 7000 or below the enUS clients 5875.
